Repository gaj23/rancid, pull requests merged in 2021-02, with the labels that each got.

#7 Gaj/styling/header touchup
  .eslintcache
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/movie-data.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Film/Film.css
  src/components/Film/Film.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/home.png
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/index.css
  src/index.js
  src/logo.svg
  src/scss/_variables.scss
Labels: MVP, enhancement

#13 Rlt/feature/format money
  .eslintcache
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Cards/Cards.css
  src/components/Cards/Cards.js
  src/components/Film/Film.css
  src/components/Film/Film.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Movies/Movies.js
Labels: MVP, enhancement

#17 Gaj/feature/error loading handling
  .eslintcache
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/movie-data.js
  src/components/Film/Film.css
  src/components/Film/Film.js
Labels: MVP, enhancement

#25 Gaj/refactor/router error
  .eslintcache
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/rancid_app_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  public/index.html
  src/api-calls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Cards/Cards.css
  src/components/Cards/Cards.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Film/Film.css
  src/components/Film/Film.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/index.js
  src/scss/_variables.scss
Labels: MVP, documentation

#27 Rlt/testing/refactor
  .eslintcache
  cypress/fixtures/Film-data.json
  cypress/fixtures/Movies-data.json
  cypress/integration/rancid_app_spec.js
  public/index.html
  src/api-calls.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Cards/Cards.css
  src/components/Cards/Cards.js
  src/components/Error/Error.js
  src/components/Film/Film.css
  src/components/Film/Film.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Movies/Movies.js
  src/index.css
  src/reportWebVitals.js
  src/setupTests.js
Labels: MVP, enhancement, testing

#29 Rlt/testing/film waiting msg
  .eslintcache
  README.md
  cypress/integration/rancid_app_spec.js
  package-lock.json
  package.json
  src/components/App/App.css
  src/index.js
Labels: MVP, bug, documentation, testing
